### ISSUE TITLE
Use check-boxes

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net-ng#32]
Using check-boxes for the [status page](https://github.com/WachterJud/qaul.net-ng/blob/qaul-ng/README_qaul.net-ng.md) could be pretty cool.

- [x] Awesome
- [x] Really cool

**Comment by MathJud** [comment]
Nice markdown feature :-) 
But I think these check-boxes should only be used for forms.

**Comment by deavmi** [comment]
@MathJud Okay :smile:.
