### ISSUE TITLE
Binaries available?

### ISSUE THREAD

**Issue by deavmi** [WachterJud/qaul.net-ng#76]
Binaries available? Anytime soon?

**Comment by MathJud** [comment]
The next binaries shall be the beta4 binaries, that are scheduled for milestone beta4 on november 31 this year.

**Comment by deavmi** [comment]
Okay. Yay! :)

**Comment by deavmi** [comment]
Thanks :smile:

**Comment by MathJud** [comment]
The current binaries are downloadable from: https://qaul.net/download/

**Comment by deavmi** [comment]
Yay! Thanks :)
